spring:
  datasource:
    username: postgres
    password: Tsunami9
    driverClassName: org.postgresql.Driver
    driverDialect: org.hibernate.dialect.PostgreSQL82Dialect
    url: jdbc:postgresql://localhost/keycloakbroker
    hikari:
      minimum-idle: 1
      maximum-pool-size: 400

server:
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true


keycloak:
  appRealm: chat
  idmBrokerAuthUrl: http://localhost:8080/auth
  idmBrokerApp: app-broker
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin